#------------------------------
# Configuration du site
# http://jekyllrb.com/docs/configuration/
title: Happy Coding
language: "fr"
baseurl: ""
url: ""
description: ''
keywords: [
    "apprendre l'informatique",
    "Python", "HTML", "CSS", "JavaScript",
    "Twitter Bootstrap", "VueJS", "Markdown"
]

twitter_username: flavien_hugs
github_username:  flavien-hugs

#-------------------
# configuration du build
debug: false
safe: true
markdown: kramdown

sass:
    load_paths:
        - _sass
        - node_modules
exclude: 
  - node_modules
  - Makefile
  - readme.md
  - package.json
  - package-lock.json
  - yarn.lock

livereload: true

#---------------------
# A propos de l'auteur
author: flavien-hugs
email: flavienhugs@pm.me
tel: (+225)51571396/77274886
