#----------------------------------------
# Configuration du site
# http://jekyllrb.com/docs/configuration/
#----------------------------------------
# A propos de l'auteur
#----------------------------------------

author: flavien-hugs
email: flavienhugs@pm.me
tel: (+225) 51 57 13 96 / 77 27 48 86
title: Happy Coding
language: "fr"
baseurl: ""
url: ""
description: "Plateforme de formation à l'outil informatique
et d'initiation à l'anglais."
keywords: [
    "apprendre l'informatique", "initiation à l'informatique",
    "Python3", "HTML", "CSS", "HTML5", "CSS3", "JavaScript",
    "Twitter Bootstrap", Markdown"
]

timezone: Africa/Nairobi

#------------
# Social Link
#------------

twitter_username: flavien_hugs
github_username: flavien-hugs
facebook_username: flavien.hugs

#-----------------------
# configuration du build
#-----------------------

markdown: kramdown
permalink: /formation/:categories/:year/:month/:title

#---------------------
# Configuration plugin
#---------------------

plugins:
    - jekyll-paginate
paginate: 20
paginate_path: "/formation/:num"

sass:
    load_paths:
        - _sass
        - node_modules
exclude: 
  - node_modules
  - Makefile
  - readme.md
  - package.json
  - package-lock.json
  - yarn.lock

livereload: true
