#----------------------------------------
# Configuration du site
# http://jekyllrb.com/docs/configuration/
#----------------------------------------

destination: _site
author: flavien-hugs
email: contact@unsta.net
tel: (+225) 015 157 1396 / 077 727 4886
title: ADN NUMÉRIQUE
language: "fr"
baseurl: "https://formation.unsta.net"
url: "https://formation.unsta.net"
description: "Plateforme de formation à l'outil informatique
et d'initiation à l'anglais."
keywords: [
    'apprendre informatique', 'initiation informatique',
    'Python', 'HTML', 'CSS', 'JavaScript', 'Jekyll',
    'Twitter Bootstrap', 'Bootstrap', 'Markdown',
]

timezone: Africa/Nairobi

#------------
# Social Link
#------------

twitter_username: flavien_hugs
github_username: flavien-hugs
facebook_username: flavien.hugs

#-----------------------
# configuration du build
#-----------------------

encoding: utf-8
markdown: kramdown
permalink: /formation/:categories/:year/:month/:title

#---------------------
# Configuration plugin
#---------------------

plugins:
    - jekyll-paginate
    - jekyll-minifier
    - jekyll-sitemap
    - jekyll-seo-tag

jekyll-minifier:
  exclude: 'atom.xml'
  uglifier_args:
    harmony: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  compress_javascript: true 

paginate: 20
paginate_path: "/formation/page:num"


#---------------------
# configuration assets
#---------------------

sass:
    load_paths:
        - _sass
        - node_modules
    style: compressed

#-----------------------
# configuration includes
#-----------------------

includes_dir : _includes
layouts_dir : _layouts

#-----------------------
# configuration excludes
#-----------------------

exclude:
  - .sass-cache
  - .jekyll-cache
  - Gemfile
  - node_modules
  - package.json
  - package-lock.json

livereload: true
